### ISSUE TITLE
Make user_data supported by ESS

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#229]
## Feature request

- Support user_data 
The ESS has already supported user_data from web console, can we support user_data in terraform provider, please?

- Support role attachment
And not sure if the role attachment would also be supported by ESS.

## Use case

A typical use case for this ESS with user_data and role would be:

Scale up a new ECS instance with proper role, which can download some scripts from a specific OSS bucket, and then write a script in the user_data to use that role and download the script from OSS to bootstrap the instance and get it ready for taking requests.

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

Thank you for your suggestion. At present, ESS API hasn't supported user-data, so we can't help it. However, I think the API also supports user_data in the near future since web console has done it, and we also will push this matter continuously. Please be patient, thanks a lot.

Regards,
He Guimin

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

ESS resource has supported ram, keypair and userdata from [v1.2.7](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.7). Besides, [v1.2.9](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.9) has supported tags. Please update it, thanks a lot.

Regards
He Guimin
