### ISSUE TITLE
Add resource for Express Connect

### ISSUE THREAD

**Issue by bittopaz** [alibaba/terraform-provider#249]
Do we have a plan to support [Express Connect](https://help.aliyun.com/product/27782.html)?

This is something like vpc_peer_connection in AWS and it is very useful when building architecture on top of several vpcs.

**Comment by xiaozhu36** [comment]
Hi @bittopaz 

We have supported one of the  Express Connect - [router interface](http://47.95.33.19:4567/docs/providers/alicloud/r/router_interface.html)  in the [latest version](https://github.com/alibaba/terraform-provider/releases/tag/V1.2.4), please update and use it.

By the way, because some lawyer reasons, if you want to use it out of China, you must activate it by its [console](https://vpc.console.aliyun.com/expressConnect?spm=5176.2020520143.103.10.6633fde7LLeS9Z#/connection/us-east-1/list).

Regards,
He Guimin
