### ISSUE TITLE
route entry does not rollback on update falirues

### ISSUE THREAD

**Issue by alexwo** [alibaba/terraform-provider#317]
Hi,
In update scenario where we would like to update a routing rule to a new one.
For instance destination_cidrblock change from 10.0.0.1/32 to 10.0.0.0.2/32.
in case the action fails because of already existing rule or some other reason the original route rule is deleted and not recovered.

the expected behavior for such case would be to keep the old routing rule if the new rule did not apply.

**Comment by xiaozhu36** [comment]
Hi @alexwo at present, provider does not support to modify destination_cidrblock, and if it is changed, provider will recreate a new one. About your feedback, could you please send me more error details? Which version is your terraform provider?

In addition, this issue we will fixed in the next version. Please be patient. Thanks a lot.
