### ISSUE TITLE
nic_type: "internet" issue in security group rule definition

### ISSUE THREAD

**Issue by firasnajjar** [alibaba/terraform-provider#765]
I'm working in a domestic account in Frankfurt region.

I'm trying to create a security group rule that enables access from a specific CIDR from the internet. 
I'm using the following code:
```
provider "alicloud" {
  access_key = "your access key"
  secret_key = "your secret key"
  region = "eu-central-1"
}

resource "alicloud_vpc" "vpc" {
  name       = "test_vpc2"
  cidr_block = "10.0.0.0/8"
}

resource "alicloud_security_group" "jumpbox_sg" {
  name        = "jumpbox_sg"
  vpc_id      = "${alicloud_vpc.vpc.id}"
}

resource "alicloud_security_group_rule" "allow_all_tcp_from_batata_to_jumpbox" {
  type              = "ingress"
  ip_protocol       = "tcp"
  nic_type          = "internet"
  policy            = "accept"
  port_range        = "1/65535"
  priority          = 1
  security_group_id = "${alicloud_security_group.jumpbox_sg.id}"
  cidr_ip           = "212.179.128.0/29"
}
```

When I run terraform apply I get the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* alicloud_security_group_rule.allow_all_tcp_from_batata_to_jumpbox: 1 error(s) occurred:

* alicloud_security_group_rule.allow_all_tcp_from_batata_to_jumpbox: When security group in the vpc or authorizing permission for source/destination security group, the nic_type must be 'intranet'.
```

The nic_type in this case is internet because the rule is for enabling access from the internet.

If I remove the nic_type from the code, which shouldn't have any effect since the default
according to your documentation here: 

https://www.terraform.io/docs/providers/alicloud/r/security_group_rule.html#nic_type

applying the changes with terraform succeeds. This is a very weird behavior!

**Comment by nightmeng** [comment]
In mutual security group authorization, when  DestGroupId is specified  and DestCidrIp is not specified,  you must set  NicType to intranet.  Default value: internet.

Please see the following link:
https://www.alibabacloud.com/help/doc-detail/53516.htm

**Comment by firasnajjar** [comment]
Does this mean that this field is not optional? It should only be set to intranet in this specific case only and otherwise it should never be set?

Usually if a field is optional, it means that it can be set. Setting it to the default value or removing it completely should have the exact same behavior!

**Comment by xiaozhu36** [comment]
HI @firasnajjar If the security group is in the VPC, its nic_type is must be intranet. If it is not in the VPC,  setting it to the default value or removing it completely has same behavior!

**Comment by xiaozhu36** [comment]
Hi @firasnajjar nic_type's default is 'internet' and it keeps up with OpenAPI [AuthorizeSecurityGroup](https://www.alibabacloud.com/help/doc-detail/25554.htm). I agree with you said "Usually if a field is optional, it means that it can be set. Setting it to the default value or removing it completely should have the exact same behavior!" . If your security group in not in vpc or  DestGroupId  is not set, it can meet your optional behavior. Otherwise, this parameter will be required for vpc or  DestGroupId's security group. 
In addition, there is no plan to change its default in short period. Sorry for the inconvenience.

I will close this pr and if you still have question, please reopen it. Thanks.
